#!/usr/bin/perl

@list = "; generated by convert2bind.pl\n";
open (FILE, "$ARGV[0]");
while (<FILE>) {
  chomp; 
  push(@list, lc($_)); #lc is lowercase
}
close (FILE);

sub uniq {
    return keys %{{ map { $_ => 1 } @_ }};
}

@uniquelist = uniq(@list);

foreach (@uniquelist) {
  $val = $_;
  if ($val =~ /^((([a-z]|[0-9]|\-)+)\.)+([a-z])+$/i)
  {
    print "zone \"$val\" in { type master ; file \"/etc/bind/db.blocked\" ; } ;\n";
  } else {
    #print "; $val\n";
  }
}
exit;

